### ISSUE TITLE
Non optimal methods in prefix.go

### ISSUE THREAD

**Issue by Keksov** [spiral/goridge#32]
Hello,

there are three special methods in prefix.go which should modify content of a Prefix variable:
```
func (p Prefix) WithFlag(flag byte) Prefix
func (p Prefix) WithFlags(flags byte) Prefix
func (p Prefix) WithSize(size uint64) Prefix
```
note that the 'p Prefix' means that a copy of a variable will be passed to the method and returned from the method, as reasonably stated in docs 'and returns NEW instance of prefix' . Searching for Prefix data type usage reveals two main places: socket.go and pipe.go (and several _test files too). 

Most common form of its usage is:
`prefix := NewPrefix().WithFlags(flags).WithSize(uint64(len(data)))`

It means that a variable created by NewPrefix() duplicated two times for each With* method call. It looks like it would be more reasonable to use pointer here:
`func (p *Prefix) WithFlag(flag byte) *Prefix`

Sure, copying of 17 bytes is not a big deal, but when you multiply it by number of processed request you may start to think - why I'm wasting my CPU and RAM? ))

PS. Some tests will fail after that

**Comment by wolfy-j** [comment]
Hi, we are going to address some of the protocol improvements in version 3.0 (including async support). 

Currently, this optimization would not give you any noticeable improvement since the bottleneck located in syscalls. You can bench it and you'll see that the difference will be within a couple of ns (do not forget the cost of *pointer).

**Comment by Keksov** [comment]
OK, I see. Closed.
